### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by JunMa11** [luogongning/PlaqueRL#1]
Dear @luogongning ,

Thanks for sharing the great work.

I can't find the dataset. 
Would it be possible for you to upload some demo data?

Best regards,
Jun

**Comment by luogongning** [comment]
OK, No problem, Waiting for two weeks! We will update the data.

**Comment by JunMa11** [comment]
Got it.
Thank you very much.

**Comment by JunMa11** [comment]
Hi @luogongning ,

Are there any updates?

best,
Jun

**Comment by luogongning** [comment]
Dear Jun @JunMa11,

Thanks for your attention. Sorry for later response. I have uploaded some demo data, wishing it useful. In fact, I am preparing a journal paper. My partner (a doctor) suggests that we will try our best to upload all the training data when the journal paper is accepted. 

best,
Gongning

**Comment by JunMa11** [comment]
Dear @luogongning 

Thanks for your kindly reply very much.

I'm so happy that you have uploaded some demo data.

I hope everything goes well with your journal paper!

best,
Jun
